### ISSUE TITLE
Issue Titles?

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-stubs#15]
Are duplicate issue titles going to be a problem?

For example, today I am going to open an issue titled "Geom::PolygonMesh" to declare my intent to begin work on that documentation.  Let's say that issue is complete and merged. A year later, if someone wants to make additional changes to that file, is it going to be a problem to use the same issue title? If so, what is a good way to differentiate titles for similar issues on the same stub?

Issues have unique #'s, so maybe duplicate titles are fine?

Is a title like "Geom::PolygonMesh Cleanup" OK, or should we try to be more specific?

**Comment by DanRathbun** [comment]
They seem to be identified by their number, not title.
> Is a title like "Geom::PolygonMesh Cleanup" OK,...

I think if you intend to methodically go through the whole class to bring it all up to the `Documentation Guide.md` standards, in one whole PR (it can be multiple commits to finish it,) then I'd say it's okay.

If you were to, say be working on the `Entities` class, that one is a really big job, and it could be divided in "Part I", "Part II", etc. So we'd want the titles to be the same except for the modifiers.

**Comment by DanRathbun** [comment]
> A year later, if someone wants to make additional changes to that file, is it going to be a problem to use the same issue title? If so, **what is a good way to differentiate titles for similar issues on the same stub?**

Once the "Cleanup" overhaul is done, we'll likely be dealing with issues on specific method output, so a tiltle like this would be the norm:

**`Geom::PolygonMesh#set_uv : Note is run-on sentence`**

**Comment by thomthom** [comment]
I'm not to fuzzed with the exact format of the issue titles etc. As long as they make sense for their topic.

That being said, for simple cleanup changes like fixing types, syntax and typos one can just create a PR without an issue. The PR becomes an issue automatically.

An issue is useful if it needs some discussion before doing work, either because you want to collect feedback or the work takes some time and you want to indicate you are working on it.

But in general I'd say to just keep it simple.

**Comment by thomthom** [comment]
Thinking of it, if you plan to start a larger PR, you can do a first small commit, then do a PR so it appear here. Then people can see what is being worked on as new commits come in.

Just an idea. I'm not going to enforce a particular workflow on this. Less process is better IMO.

**Comment by jimfoltz** [comment]
> Then people can see what is being worked on as new commits come in.

I added your and Dan and SketchUp repos as remotes to my local fork. Then I can `git fetch --all` and your branches get added to my repo. I can then `git checkout` the remote branches and build the docs. 

![00052](https://cloud.githubusercontent.com/assets/137514/22185775/88212ed2-e0b9-11e6-9e94-11cf610f0357.png)

**Comment by DanRathbun** [comment]
_OffTopic_
 >Sounds scary. (And this is not really about "Issue Titles")

**Comment by DanRathbun** [comment]
> @thomthom: That being said, for simple cleanup changes like fixing types, syntax and typos one can just create a PR without an issue. The PR becomes an issue automatically.

I disagree. The PRs (although they share numbers from the same ordinal set as issues, are not issues, and are accessed separately, and kept separately. (They have separate URLs, ie ... `"/issue/32"` and `"/pull/33"`, etc.)

The average reader who is not GitHub "literate" would not expect (or know) to also look through the PR lists, to see if the bug of interest has been logged, worked, assigned or fixed in a pending PR.

**Comment by thomthom** [comment]
Closing stale issue.
