### ISSUE TITLE
Use WebDialog to draw a face in Sketchup.

### ISSUE THREAD

**Issue by sam75782008** [SketchUp/ruby-api-stubs#35]
Hello:

I am a rookie for both Ruby and Javascript, and I am recently trying to use WebDialog to draw a face in Sketchup.

I followed the example .html file and .rb file on the book "Automatic SketchUp Creating 3-D Models in Ruby" but just couldn't success drawing a face.

The WebDialog can be shown in the way that is same as the example, but just won't draw.

Here are the codes for my .html and .rb.
#================================================================
![html1](https://cloud.githubusercontent.com/assets/28663196/26021818/7f56af9c-374a-11e7-8b5a-cc16950d6d70.JPG)
![html2](https://cloud.githubusercontent.com/assets/28663196/26021819/81422fb6-374a-11e7-9efd-2db6f32a4d28.JPG)

#==================================================================

#==================================================================
![ruby](https://cloud.githubusercontent.com/assets/28663196/26021820/8586cdac-374a-11e7-864a-2a7cf346dc01.JPG)

#==================================================================
![result](https://cloud.githubusercontent.com/assets/28663196/26020928/eff11960-3739-11e7-9432-da4f741668ed.JPG)

The result is shown here. Although it shows the dialog exactly, it just won't draw a face.

I really have no idea what is wrong.

Thanks for your time. I really appreciate that.

With appreciation

**Comment by Aerilius** [comment]
There is a typo: strings respond to a method `strip` but don't know `stript`. I seem to have a different version of the book, so I can't tell whether it was maybe there (regarding the book, it uses a somewhat dated coding style, please carefully read a [style guide](https://github.com/bbatsov/ruby-style-guide)). Webdialog callbacks are not triggered from the console or the initial loading. Because of this (like SketchUp observer callbacks), they don't print errors unless you catch them with `begin … rescue … end`.

Besides this, you are more likely to get a engaged and timely response in the [support forum](https://forums.sketchup.com/c/developers/ruby-api). This question is not really an issue of this github project.

**Comment by thomthom** [comment]
It would also help to post the code as text instead of screenshots. Helps to be able to run the example. I doubt many are willing to re-create the code from the images.

**Comment by DanRathbun** [comment]
>Besides this, you are more likely to get a engaged and timely response in the [support forum](https://forums.sketchup.com/c/developers/ruby-api). This question is not really an issue of this github project.
**Agree**. This non-issue **should be closed**. @sam75782008 should use the [public forum](https://forums.sketchup.com/c/developers/ruby-api) for questions like this.

**Comment by DanRathbun** [comment]
And I just also noticed that the Ruby-side callback is named `"creat_face"`, but the JS-side protocol string has `"window.location = 'skp:create_face@' + arg;"`.

**So, `"creat_face" != "create_face"`**
