### ISSUE TITLE
Commit Authors?

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-stubs#4]
If you look at the commit log for practically every other project on GitHub such as the [ruby-syle-guide](https://github.com/bbatsov/ruby-style-guide/commits/master), each author of a pull request is credited for the the changes.  

Now look at [this repo's commit log](https://github.com/SketchUp/ruby-api-stubs/commits/master).

I think I would prefer if the merges were done in a way that acknowledged the community contributions.

**Comment by thomthom** [comment]
Hm... This is a challenge for this repo - as we have to merge the content back to our source an regen from that.

We can add contribution list of people who have submitted contributions?

**Comment by thomthom** [comment]
Maybe we can merge into a dev branch? Would that work without adding too much complexity?

**Comment by thomthom** [comment]
@jimfoltz what's your thoughts on this? What would work for you?

**Comment by jimfoltz** [comment]
Don't make it more complex than it needs to be.   I don't understand how merging to a dev branch is different than merging to any other branch including `master`?

**Comment by thomthom** [comment]
My main concern about merging to master was that it could be confusing, as we need to push the regenerated doc back into master. You'd then get two commit into the master. Maybe I'm overthinking this.

**Comment by thomthom** [comment]
So here is one issue:

Our tool work such that when there is a pull request we check out the dev branch submitted for the PR. The tool then makes a diff against the master branch. The tool then backports it to our source and we regenerate the docs and stubs.

If we then were to merge the PR into the master branch we'd run into conflicts, because the PR would merge changes clashing with the ones we regenerates.

**Comment by thomthom** [comment]
That's why I'm wondering if merging into a staging folder would work... 

For theorized workflow:

1. Check our PR and run tool to regenerate docs and stubs. This checks into master.
2. Pull PR into staging.
3. Merge master into staging to make sure staging is up to date. (I'm a little unsure if we end up with the same merge conflicts here or if Git is able to resolve)

**Comment by thomthom** [comment]
@jimfoltz I've been merging PR into "staging" as they have been coming in. This is reflected in the commit log for the branch: https://github.com/SketchUp/ruby-api-stubs/commits/staging

Is that working for you?

**Comment by jimfoltz** [comment]
I want you to manage the pull requests/merges in the way that makes the most sense for you so they can be a quick and efficient use of your time.  I appreciate the consideration - I'm good.
